# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mighty_app', '0003_order_server'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='complete',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paid',
            new_name='is_paid',
        ),
    ]
