# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mighty_app', '0005_auto_20160708_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order_menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mighty_app.MenuItem')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_items',
            field=models.ManyToManyField(to='mighty_app.OrderLine'),
        ),
    ]
